### PR TITLE
Jshint to eslint

### PR DESCRIPTION
**Pull request by brettz9**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Dropping jshint in favor of more actively maintained eslint.

### CODE REVIEW

**Comment by brettz9** [comment]
I've rebased and also amended to follow the semantic-release commenting style.

Thank you so much for setting that up!

I note though that while the tag 2.3.0 was just added to the latest on `master`, per https://www.npmjs.com/package/badge-up , the last release was already done as 2.3.0 (and that release is described as being 3 years ago).

**Comment by tkyi** [comment]
Ah I didn't get it working quite just yet. 
I manually pushed out the v2.3.0 git tag since it was missing from git.
Hoping the next commit triggers semantic release successfully

**Comment by okuryu** [comment]
You can remove more config in package.json file:
https://github.com/yahoo/badge-up/blob/9ee937b9925c0b4c31779453a6631618db7cf034/package.json#L40-L42

**Comment by brettz9** [comment]
Cool---will presumably need to be a `fix`, `feat`, or `BREAKING CHANGE` though as otherwise a `chore` like in this PR wouldn't trigger it.

Btw, do you want a PR to add `engines` to `package.json`? I find it helpful to know what versions the project should support. I could peg it to the lowest Node version (0.1.14) so it wouldn't be a breaking change, and I could call that a `feat`?

**Comment by brettz9** [comment]
@okuryu : Thanks, I've amended (and also removed a remaining jshint directive found on searching through the project files).

**Comment by tkyi** [comment]
@brettz9  yes I would love to have `engines` added to `package.json`. Not sure if we should just say node 12 since we have it running on that in the screwdriver.yaml or leave it as the lowest version as you say for now.

I generally default to `fix` unless it's a bigger feature or change.

**Comment by tkyi** [comment]
I just did a manual publish in npm so hopefully the next run will be successful at publishing with semantic release 🤞

**Comment by brettz9** [comment]
@tkyi : You let me know which `engines` to go for. I'd hope it could at least support Node 10 though as that hasn't yet reached end-of-life, and I know I have packages not requiring Node 12.

Just note that if you do want to go with `engines` set to anything other than the earliest versions, then it really should have the `BREAKING CHANGE:` syntax added in the description.

**Comment by tkyi** [comment]
@brettz9 Let's say node 10 and up
Since the pipeline is not building on super old node versions, I'm not confident we can say we support those, but node10 seems reasonable

**Comment by brettz9** [comment]
I've filed #20 to address that issue.

**Review by tkyi — APPROVED** [review]

**Pull request merged**
