### PR TITLE
Using svgo 1.2.2

### PR DESCRIPTION
**Pull request by justbrody**
To solve the high vulnerability 'Code Injection' from js-yaml.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by justbrody** [comment]
https://github.com/yahoo/badge-up/issues/8

**Comment by justbrody** [comment]
No problem, it's gone.

**Comment by justbrody** [comment]
@d2lam Could you please look at it?

**Pull request merged**
