### PR TITLE
Npm and testing

### LINKED ISSUE #8: Outdated dependency 'svgo'
The old version contains the package js-yaml which contains a high vulnerability,

### PR DESCRIPTION
**Pull request by brettz9**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Fixes #8.

Besides one dependency (svgo) having one high and two moderate vulnerabilities, the devDeps had 1 critical and 34 high vulnerabilities.

Please ensure something like this is merged, as users really deserve a fast turnaround for security issues. Thanks!

### CODE REVIEW

**Comment by brettz9** [comment]
Is this repo still being maintained?

**Comment by dholbach** [comment]
Bump?

**Comment by brettz9** [comment]
@stjohnjohnson , @frodelu , @tkyi , @justbrody , @drewfish : whoever has access--can you either resolve this vulnerability or deprecate your library?

**Comment by frodelu** [comment]
@brettz9 I don't maintain this repo as such, but will try to resurrect it and get back to you.

That said; when I run your branch locally, the four badge tests are failing with the same type of diff with change of order between the linearGradient and style elements:
```xml
<defs>
	<linearGradient id="smooth" x2="0" y2="100%">
		<stop offset="0" stop-color="#aaa" stop-opacity=".1"/>
		<stop offset="1" stop-opacity=".1"/>
	</linearGradient>
	<style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style>
(...)
```

vs

```xml
<defs>
	<style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style>
	<linearGradient id="smooth" x2="0" y2="100%">
		<stop offset="0" stop-color="#aaa" stop-opacity=".1"/>
		<stop offset="1" stop-opacity=".1"/>
	</linearGradient>
(...)
```

I'm no node.js expert, but could this simply be a change in the underlying SVG library used? Are you seeing the same errors on your end or are some of my local dependencies off?

**Comment by frodelu** [comment]
This diff made all tests pass on my end:
```diff
diff --git a/test/testData/v2-example.svg b/test/testData/v2-example.svg
index 5d792fc..519e74f 100644
--- a/test/testData/v2-example.svg
+++ b/test/testData/v2-example.svg
@@ -1 +1 @@
-<svg xmlns="http://www.w3.org/2000/svg" width="219" height="32"><defs><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h70v32H0z"/><path fill="orange" d="M70 0h30v32H70z"/><path fill="olive" stroke="#fff" d="M100 0h86v32h-86z"/><path fill="#ffe4b5" d="M186 0h33v32h-33z"/><path fill="url(#smooth)" d="M0 0h219v32H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo/far;fun</text><text class="high" x="5" y="14">foo/far;fun</text><text class="shadow" x="75.5" y="15">bar</text><text class="high" x="75" y="14">bar</text><text class="shadow" x="75.5" y="27">baz</text><text class="high" x="75" y="26">baz</text><text class="shadow" x="105.5" y="15">mork &quot;mindy&quot;</text><text class="high" x="105" y="14">mork &quot;mindy&quot;</text><text class="shadow" x="191.5" y="15">&lt;∀&gt;</text><text class="high" x="191" y="14">&lt;∀&gt;</text></g></svg>
+<svg xmlns="http://www.w3.org/2000/svg" width="219" height="32"><defs><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h70v32H0z"/><path fill="orange" d="M70 0h30v32H70z"/><path fill="olive" stroke="#fff" d="M100 0h86v32h-86z"/><path fill="#ffe4b5" d="M186 0h33v32h-33z"/><path fill="url(#smooth)" d="M0 0h219v32H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo/far;fun</text><text class="high" x="5" y="14">foo/far;fun</text><text class="shadow" x="75.5" y="15">bar</text><text class="high" x="75" y="14">bar</text><text class="shadow" x="75.5" y="27">baz</text><text class="high" x="75" y="26">baz</text><text class="shadow" x="105.5" y="15">mork &quot;mindy&quot;</text><text class="high" x="105" y="14">mork &quot;mindy&quot;</text><text class="shadow" x="191.5" y="15">&lt;∀&gt;</text><text class="high" x="191" y="14">&lt;∀&gt;</text></g></svg>
diff --git a/test/testData/v2-foo-bar-stroke.svg b/test/testData/v2-foo-bar-stroke.svg
index cbf9a09..2584e41 100644
--- a/test/testData/v2-foo-bar-stroke.svg
+++ b/test/testData/v2-foo-bar-stroke.svg
@@ -1 +1 @@
-<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#d3d3d3" stroke="#fff" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
+<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#d3d3d3" stroke="#fff" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
diff --git a/test/testData/v2-foo-bar.svg b/test/testData/v2-foo-bar.svg
index 71deae9..9542bbd 100644
--- a/test/testData/v2-foo-bar.svg
+++ b/test/testData/v2-foo-bar.svg
@@ -1 +1 @@
-<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#d3d3d3" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
+<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#d3d3d3" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
diff --git a/test/testData/v2-one-color.svg b/test/testData/v2-one-color.svg
index cde1655..25b0883 100644
--- a/test/testData/v2-one-color.svg
+++ b/test/testData/v2-one-color.svg
@@ -1 +1 @@
-<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#90ee90" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
+<svg xmlns="http://www.w3.org/2000/svg" width="57" height="20"><defs><linearGradient id="smooth" x2="0" y2="100%"><stop offset="0" stop-color="#aaa" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><style>text{font-size:11px;font-family:Verdana,DejaVu Sans,Geneva,sans-serif}text.shadow{fill:#010101;fill-opacity:.3}text.high{fill:#fff}</style><mask id="round"><rect width="100%" height="100%" rx="3" fill="#fff"/></mask></defs><g id="bg" mask="url(#round)"><path fill="#696969" d="M0 0h28v20H0z"/><path fill="#90ee90" d="M28 0h29v20H28z"/><path fill="url(#smooth)" d="M0 0h57v20H0z"/></g><g id="fg"><text class="shadow" x="5.5" y="15">foo</text><text class="high" x="5" y="14">foo</text><text class="shadow" x="33.5" y="15">bar</text><text class="high" x="33" y="14">bar</text></g></svg>
```

**Comment by brettz9** [comment]
Thank you so much for looking into this.

Heading off to bed now, but can I ask if you get the same results in changing the instantiation of `svgo` in `v2.js` (i.e., line 13) to:

```js
    svgo = new SVGO({
        plugins: [{
            sortDefsChildren: false
        }]
    }),
```

I would suspect that might be our issue. It seems my environment is just different (whether due to being a Mac or due to different npm package versions (incidentally, that'd argue, imo, for including `package-lock.json` in the repo to control the variables).

(FWIW, In doing a quick look at [the plugin](https://github.com/svg/svgo/blob/master/plugins/sortDefsChildren.js), I don't see anything immediately glaring that may be causing an inconsistency across environments. `/node_modules/svgo/lib/svgo/svg2js.js` looks to be where the conversion occurs (and that relies on `sax`). Anyways, if you see no difference, I would think it may be enough to disable this particular optimization (which seems to have been a more recent addition as well).)

**Comment by frodelu** [comment]
Seems you are correct; when explicitly disabling `svgo` as you proposed, the original tests pass. Probably better to being explicit than changing the tests work in one case and not the other.

Looking at [the repo](https://github.com/svg/svgo/), it seems the commit in svg/svgo@cc9ad33082c11044e175c806b37620d5ac4289f4 8 months ago (which seems to be released as version 1.3.2?) enabled `sortDefsChildren` by default and I just checked that I've got 1.3.2 on my computer. Per `package.json`, though, only version 1.2.2 or higher is required, so if you have a version pre 1.3.2 in your environment, that would explain the difference?

**Comment by brettz9** [comment]
@frodelu : Fair guess re: svgo version, but I also have 1.3.2 installed.

I've gone ahead and rebased (to avoid the back-and-forth in changing then reverting the test removals) with a further minor npm update and to disable the svgo optimization that was providing inconsistent results.

So I think this is now ready again.

If anyone ever wanted to dig into the cause of the inconsistency (so the optimization could be added back and as needed the issue reported to svgo), it'd probably easier to do so by someone experiencing a lack of success for the reordering, so they could find why it is *not* reordering for them (the optimization is supposed to do reordering).

**Comment by dholbach** [comment]
Super. Can this be rolled into a release too? :rocket:

**Comment by brettz9** [comment]
@dholbach : I was hoping maybe someone could look at #11 first, as it is fairly straightforward I think in just allowing an optional `Promise` return value. If not though, a release would be great just for this.

**Pull request merged**
