### PR TITLE
ES6 Promise option

### PR DESCRIPTION
**Pull request by brettz9**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Returns a Promise, making the callback optional (for v1 and v2).

Even if, as per #3, you still want to support other Promise implementations (not as commonly used these days with ES6 Promises being widely adopted, I'd think), it would be nice to add this simple ES6 Promise-compatible addition in the interim.

### CODE REVIEW

**Comment by brettz9** [comment]
@frodelu : Thank you kindly for the merge in #10. I've rebased this PR on top of that now.

**Comment by brettz9** [comment]
Also with @stjohnjohnson not having responded in #10 , I'm wondering whether he (or anyone) is available to address https://github.com/stjohnjohnson/jenkins-mocha/issues/42 (which is another vulnerability for your devDeps.). If `jenkins-mocha` is not being maintained, perhaps this devDep. can be changed. (There is a `mocha-multi-reporters` allowing multiple mocha reporters, but that seems unmaintained as well; I have added a fork which got that working and extended but haven't made a separate package for it to this point though I could if there were interest to use it.)

**Comment by tkyi** [comment]
@brettz9 We have been replacing `jenkins-mocha` with `mocha` and `nyc` directly in our org: https://github.com/screwdriver-cd/screwdriver/pull/1957/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
maybe this could be done for badge-up too?

**Comment by brettz9** [comment]
@tkyi : Thank you, sounds great to me! Filed #14...

**Pull request merged**
