### PR TITLE
Add stroke attributes

### PR DESCRIPTION
**Pull request by frodelu**
Add support for stroke attributes for sections in the format of `s{color}` where color is either hex code or CSS color.

### CODE REVIEW

**Comment by drewfish** [comment]
nice!

**Comment by frodelu** [comment]
Seems Travis CI build was never configured correctly and is expected to fail. At least that's what's stated in PR #4.

@drewfish : Any chance we could get this merged?

**Comment by drewfish** [comment]
Alas I don't have merge perms since I'm just a contributor. @stjohnjohnson any chance you could merge this?

**Comment by frodelu** [comment]
@stjohnjohnson : pinging again hoping you could merge this. 😄

**Comment by stjohnjohnson** [comment]
I'll fix the Travis integration by switching to SD in #6

**Comment by stjohnjohnson** [comment]
+ badge-up@2.3.0

**Pull request merged**
